repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        files: "^(fastapi_app|rag|ml)/"
        additional_dependencies:
          - types-requests
          - pydantic

  - repo: https://github.com/pypa/pip-audit
    rev: v2.9.0
    hooks:
      - id: pip-audit
        args: ["--strict"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
codex/locate-and-fix-critical-bug-4f0qez
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args:
          - -q
          - -r
          - fastapi_app
          - -x
          - tests,__pycache__,.venv,build,dist
          - --severity-level
          - medium
          - --confidence-level
          - medium
=======
  # Bandit as a local hook (CI also runs Bandit)
  - repo: local
    hooks:
      - id: bandit
        name: bandit
        entry: bandit -q -r fastapi_app -x tests,__pycache__ --severity-level medium --confidence-level medium
        language: system
        types: [python]
 main
        pass_filenames: false
