name: API Fuzz
on:
  pull_request:
  push:
jobs:
  schemathesis:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}
      FUZZ_MODE: 'true'
      RATE_LIMIT_QPS: '1000000'
      REQUEST_BODY_MAX_BYTES: '10485760'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt schemathesis[fastapi]
      - name: Schemathesis (ASGI app)
        run: |
          schemathesis run --app fastapi_app.app.main:app /openapi.json \
            --workers=1 --checks=all \
            --hypothesis-max-examples=25 --hypothesis-deadline=none --hypothesis-seed=1337 \
            --experimental=openapi-3.1
