name: CI
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: true

jobs:
  tests:
    name: tests (py${{ matrix.python-version }})
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "**/requirements*.txt"
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements.txt -r requirements-dev.txt
      - run: python -m ruff check .
      - run: python -m black --check .
      - run: python -m mypy fastapi_app
      - run: pytest -q
      - run: coverage xml || true
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
