name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      GIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt -r requirements-dev.txt
      - name: Lint + Format check
        run: |
          python -m ruff check .
          python -m black --check .
      - name: Type check
        run: python -m mypy fastapi_app rag ml
      - name: Tests (with coverage gate)
        run: python -m pytest
