name: Evals & SBOM
on:
  push:
  pull_request:
jobs:
  eval-lite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run lite retrieval eval
        run: python rag/eval_metrics.py
      - name: Upload eval report
        uses: actions/upload-artifact@v4
        with: { name: eval-lite-report, path: rag/eval/report.json }

  ragas:
    runs-on: ubuntu-latest
    if: ${{ secrets.OPENAI_API_KEY != '' || secrets.ANTHROPIC_API_KEY != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: RAGAS eval (conditional)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: python rag/eval_ragas.py

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Generate CycloneDX SBOM
        run: |
          python -m pip install --upgrade pip
          python -m pip install cyclonedx-bom
          cyclonedx-py --e pip --output sbom.xml
      - uses: actions/upload-artifact@v4
        with: { name: sbom-cyclonedx, path: sbom.xml }
