name: retrieval-evals

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: retrieval-evals-${{ github.ref }}
  cancel-in-progress: true

jobs:
  evals:
    runs-on: ubuntu-latest
    env:
      USE_DUMMY_EMBEDDINGS: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: '**/requirements*.txt'
      - name: Cache HF models
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface
          key: hf-${{ hashFiles('requirements.txt') }}
      - name: Install deps
        run: |
          pip install -U pip
          pip install -r requirements.txt -r requirements-dev.txt sentence-transformers
          pip install faiss-cpu || true
      - name: eval bm25
        run: python scripts/eval_retrieval.py --backend bm25 --k 10
      - name: artifact bm25
        uses: actions/upload-artifact@v4
        with:
          name: eval-bm25
          path: evals/latest.json
      - name: eval embed
        run: python scripts/eval_retrieval.py --backend embed --k 10
      - name: artifact embed
        uses: actions/upload-artifact@v4
        with:
          name: eval-embed
          path: evals/latest.json
      - name: eval hybrid
        run: python scripts/eval_retrieval.py --backend hybrid --k 10
      - name: artifact hybrid
        uses: actions/upload-artifact@v4
        with:
          name: eval-hybrid
          path: evals/latest.json
      - name: compare to baseline
        run: python scripts/compare_eval.py --current evals/latest.json --baseline evals/baseline.json
      - name: artifact latest
        uses: actions/upload-artifact@v4
        with:
          name: eval-latest
          path: evals/latest.json
