name: Security
on:
  pull_request:
  push:
jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements-dev.txt
      - name: Bandit (High severity)
        run: bandit -q -r fastapi_app -lll
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -U pip
      - run: python -m pip install -r requirements-dev.txt
      - name: Semgrep (FastAPI + Python)
        run: semgrep --error --severity=ERROR --config p/python --config p/fastapi
